import { useMemo, useState } from "react";
import { ArrowSquareOut, FloppyDisk, MagnifyingGlass, Trash } from "@phosphor-icons/react";
import { useAppData } from "../AppDataContext";
import { normalizeHarajUrl, removeAd, updateAd } from "../data";
import { adBranchId, formatDateArabic, getWeekStartKey, isOverdue } from "../schedule";
import { AD_STATUS_LABELS, type AdStatus, type HarajAd } from "../types";
import { ConfirmButton, EmptyState, PageTitle } from "../components/Ui";
import { AdCopyCard } from "../components/AdCopyCard";

const statuses: AdStatus[] = ["assigned", "published", "approved", "needs_fix", "closed"];
function Editor({ ad }: { ad: HarajAd }) {
  const [url, setUrl] = useState(ad.url || ""); const [notes, setNotes] = useState(ad.notes || ""); const [saving, setSaving] = useState(false);
  async function save() { setSaving(true); try { const clean = normalizeHarajUrl(url); const patch: Partial<HarajAd> = { url: clean, notes: notes.trim() }; if (clean && ad.status === "assigned") patch.status = "published"; await updateAd(ad.id, patch); } finally { setSaving(false); } }
  return <div className="ad-editor"><input className="url-input" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://haraj.com.sa/..." /><input value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="ملاحظة داخلية" /><button className="secondary-button compact" onClick={() => void save()} disabled={saving}><FloppyDisk size={17} />{saving ? "حفظ..." : "حفظ"}</button>{ad.url ? <a className="link-button" href={ad.url} target="_blank" rel="noreferrer"><ArrowSquareOut size={17} />فتح</a> : null}</div>;
}

export function AdsPage() {
  const { accounts, agents, ads, publishingSettings } = useAppData();
  const [search, setSearch] = useState(""); const [status, setStatus] = useState<"all" | AdStatus>("all"); const [branchId, setBranchId] = useState("all"); const [agentId, setAgentId] = useState("all"); const [urlFilter, setUrlFilter] = useState<"all" | "with" | "without">("all"); const [specs, setSpecs] = useState<"all" | "matched" | "partial" | "missing">("all"); const [weekFilter, setWeekFilter] = useState<"all" | "current">("all");
  const currentWeek = getWeekStartKey(); const branchById = useMemo(() => new Map(accounts.map((x) => [x.id, x])), [accounts]); const agentById = useMemo(() => new Map(agents.map((x) => [x.id, x])), [agents]);
  const rows = useMemo(() => { const needle = search.trim().toLowerCase(); return ads.filter((ad) => {
    if (status !== "all" && ad.status !== status) return false; if (branchId !== "all" && adBranchId(ad) !== branchId) return false; if (agentId !== "all" && ad.agentId !== agentId) return false;
    if (urlFilter === "with" && !ad.url) return false; if (urlFilter === "without" && ad.url) return false; if (specs !== "all" && ad.specsStatus !== specs) return false; if (weekFilter === "current" && ad.weekStart !== currentWeek) return false;
    if (!needle) return true; const bag = `${ad.carName} ${ad.statement} ${ad.modelYear} ${ad.adTitle || ""} ${ad.adText || ""} ${branchById.get(adBranchId(ad))?.name || ""} ${agentById.get(ad.agentId)?.name || ""}`.toLowerCase(); return bag.includes(needle);
  }); }, [ads, status, branchId, agentId, urlFilter, specs, weekFilter, search, currentWeek, branchById, agentById]);

  return <>
    <PageTitle title="الإعلانات" subtitle={`كل صيغة إعلان محفوظة مع التكليف كما تم تسليمها للمندوب. حساب حراج الحالي: ${publishingSettings.accountName || "غير محدد"}.`} />
    <div className="filters-bar multi"><label className="search-box"><MagnifyingGlass size={19} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="بحث بالسيارة أو المندوب أو نص الإعلان" /></label><select value={weekFilter} onChange={(e) => setWeekFilter(e.target.value as typeof weekFilter)}><option value="all">كل الفترات</option><option value="current">الفترة الحالية</option></select><select value={status} onChange={(e) => setStatus(e.target.value as typeof status)}><option value="all">كل الحالات</option>{statuses.map((x) => <option key={x} value={x}>{AD_STATUS_LABELS[x]}</option>)}</select><select value={branchId} onChange={(e) => setBranchId(e.target.value)}><option value="all">كل الفروع</option>{accounts.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={agentId} onChange={(e) => setAgentId(e.target.value)}><option value="all">كل المناديب</option>{agents.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={specs} onChange={(e) => setSpecs(e.target.value as typeof specs)}><option value="all">كل حالات المواصفات</option><option value="matched">CompareKey كامل</option><option value="partial">CompareKey جزئي</option><option value="missing">CompareKey غير جاهز</option></select><select value={urlFilter} onChange={(e) => setUrlFilter(e.target.value as typeof urlFilter)}><option value="all">كل الروابط</option><option value="with">برابط</option><option value="without">بدون رابط</option></select></div>
    <section className="panel table-panel">{!rows.length ? <EmptyState title="لا توجد إعلانات" text="أنشئ جدول نشر من مخزون السيارات." /> : <div className="table-scroll"><table className="ads-table ad-copy-table"><thead><tr><th>موعد النشر</th><th>السيارة</th><th>الفرع / المندوب</th><th>صيغة الإعلان</th><th>الحالة</th><th>الرابط والملاحظات</th><th></th></tr></thead><tbody>{rows.map((ad) => { const late = isOverdue(ad); return <tr key={ad.id} className={late ? "late-row" : ""}><td>{ad.scheduledDate ? <div className="schedule-date-cell"><strong>{formatDateArabic(ad.scheduledDate, { weekday: "short", day: "numeric", month: "short" })}</strong>{late ? <span>متأخر</span> : null}</div> : "—"}</td><td><strong>{ad.carName}</strong><small className="cell-sub">{ad.statement} · {ad.modelYear}</small><small className="cell-sub">حراج: {ad.harajAccountName || publishingSettings.accountName || "—"}</small></td><td><strong>{agentById.get(ad.agentId)?.name || "مندوب محذوف"}</strong><small className="cell-sub">{branchById.get(adBranchId(ad))?.name || "بدون فرع"}</small></td><td className="copy-cell"><AdCopyCard ad={ad} compact /></td><td><select className={`status-select ${ad.status}`} value={ad.status} onChange={(e) => void updateAd(ad.id, { status: e.target.value as AdStatus })}>{statuses.map((x) => <option key={x} value={x}>{AD_STATUS_LABELS[x]}</option>)}</select></td><td><Editor ad={ad} /></td><td><ConfirmButton className="icon-danger" confirmText="حذف التكليف؟" onConfirm={() => removeAd(ad.id)}><Trash size={16} /></ConfirmButton></td></tr>; })}</tbody></table></div>}</section>
  </>;
}
